### ISSUE TITLE
Include service name and host name in grpc metrics tags

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-templates#14]

**Comment by dougfort** [comment]
Here is a sample run

![image](https://user-images.githubusercontent.com/17745/35341166-041db6fe-00f3-11e8-8103-97326189dbac.png)

**Comment by dougfort** [comment]
* test_service is service name
* pop-os is post name
* method name is protobuf/TestService-HelloStream, etc

**Comment by joshua-rutherford** [comment]
Hmm, this is better but what if I have two instance of this service running.  Can I distinguish the two?

**Comment by dougfort** [comment]
I've poked around in the gRPC docs. I don't see any identifier in addition to service name. We could use host:port which is unique. 

I think that the place where service instances would be distinguished is at a higher level, like docker container id, kubernetes node or whatever AWS has. We could add value by capturing that and passing it to statsd.

Or we could generate our own service instance id.

**Comment by joshua-rutherford** [comment]
Sorry to reopen but I don't think this discussion is closed yet.  As this stands, the metrics are pretty useless.  If I have six instances of a service running and they are all pumping metrics with the same exact keys and labels then I'll have no use for these metrics as I won't be able to correlate them with an individual or generate aggregates. So while the 'host_name' requirement may not be achievable I still need a unique way to identify instances.  

This is not an issue for scrape endpoints like Prometheus as it can be configured per scrape, but for push metrics it's a must.

If I'm to use something like container id, how would I get it into the metrics?

**Comment by dougfort** [comment]
I just wanted to merge the PR, because it is much better than what was there before. We can use this issue, or open another issue, but I expect to spend a lot of iterations getting this right.

**Comment by dougfort** [comment]
Here are some possibilities for identifying :
 * we could use these server's address
 * we could generate a UUID from "github.com/google/uuid"
 * we could use the host and port we send to zookeeper
