### ISSUE TITLE
Shell nits in templates

### ISSUE THREAD

**Issue by cstrahan** [DecipherNow/gm-fabric-templates#52]
Some improvements to make in generated shell scripts, found while reviewing https://github.com/DecipherNow/gm-fabric-apitest/pull/36.

---

https://github.com/DecipherNow/gm-fabric-templates/blob/c74a4fe522d93ab2e080932fd5286fa8567f4f0c/default/templates/docker/entrypoint.sh#L5

We should prefix that line with `exec ` -- that'll save us a `fork`, resulting in one process rather than two.

https://github.com/DecipherNow/gm-fabric-templates/blob/c74a4fe522d93ab2e080932fd5286fa8567f4f0c/default/templates/build_server.sh#L7

We should add `GOPATH="${GOPATH:-$HOME/go}"` after this line, to make things a little more robust. `$HOME/go` is the default path that all `go` tools use when `$GOPATH` isn't set.

**Comment by cstrahan** [comment]
@rfielding pointed out in slack that `$GOPATH` is a list of colon separated paths, so wherever we want to treat `$GOPATH` as the path (singular) where e.g. `go get` would put something, we should use something like  `$GOPATH/bin`, we should use something like `GOPATH_FIRST=$(echo $GOPATH | cut -d: -f1)`

**Comment by rfielding** [comment]
Note that even though the slack container adds a second path into GOPATH, it is even a non-existent path.  The specification _does_ at least promise that the first path is where read/writes go (ie: go get).  In some cases, it might be better to do something like `GOPATH=$(echo $GOPATH | cut -d: -f1)` in the beginning to avoid a lot of code rewrites.
